### ISSUE TITLE
KP125 Polling Interval and energy-monitoring alerts

### ISSUE THREAD

**Issue by snarkywolverine** [DaveGut/HubitatActive#25]
I have a Kasa KP125, which supports energy monitoring. My goal is to have hubitat send me alerts whenever the power draw drops below a threshold (i.e., the downstream device is turned off).

I have configured a static IP (via DHCP lease) on my router for my Kasa plug, which has driver version 6.6.0, and the plug is set to control via LOCAL (not cloud). However, I'm seeing a couple of things I can't quite make sense of -- and the troubleshooting guide didn't really help with.

(1) I tried to change the setPollInterval in the dropdown to something other than 30 minutes, but it seems I can't.  After changing the dropdown, I've tried to hit 'save device' or 'save preferences' to lock in a new time window, but upon refresh, the setting is still set to 'default' in the dropdown, and 30 minutes in the "State Variables" section.

(2) In the event logs, I saw a few log entries for power and energy usage, but the last one was over a week ago - I'm not sure how to troubleshoot this (I don't see any failure events either).  Would log values show up if the switch was in the 'off' state? What if it were switched on manually (at the plug)?

In the course of troubleshooting, I tried to use the IP Comms test tool - but it showed no Kasa devices installed (???).  However, when I go to the switch in Hubitat, I can still turn it on/off (the switch responds accordingly, and the logs show a switch on/off event).  Note: I didn't reset the device DB, since I still have basic communication with the devices (but am happy to if that would make a difference here).

I can enable debug logs and try some things if that helps - but how would I retrieve those debug logs -- are they written to the same events view, or are they in a different location to retrieve?

I've only had the kasa plugs for a couple weeks - looking forward to getting them to be more stable.  Any wisdom here?

**Comment by DaveGut** [comment]
"(1) I tried to change the setPollInterval in the dropdown to something other than 30 minutes, but it seems I can't. After changing the dropdown, I've tried to hit 'save device' or 'save preferences' to lock in a new time window, but upon refresh, the setting is still set to 'default' in the dropdown, and 30 minutes in the "State Variables" section."

- Could not duplicate on my system.
- To change the poll interval, To set the poll interval, select the desired interval from the drop down and then press the button (setPollInterval).  
- Then reload your browser page.
- After reloading the page, the state.pollInterval in the state variables section and the schedule at the bottom should reflect the new interval.
- The value in the set poll interval may not contain the current setting.  It may have "default".
- 

"(2) In the event logs, I saw a few log entries for power and energy usage, but the last one was over a week ago - I'm not sure how to troubleshoot this (I don't see any failure events either). Would log values show up if the switch was in the 'off' state? What if it were switched on manually (at the plug)?"

- Could not duplicate.
- The log values only change when the attribute value changes.  So, em logs will only appear if EM function is on and the energy values are changing during the polling.
- To verify EM Functions:
  - Select "Enable Energy Monitor" in preferences and Save Preferences
  - Wait bottom minutes, the reload your browser page.
  - Look at the bottom "Scheduled Jobs" and you will see four scheduled jobs: getEnergyLastMonth, getEnergyThisMonth, poll, and getEnergyToday.  If these are there, then all is good.

"In the course of troubleshooting, I tried to use the IP Comms test tool - but it showed no Kasa devices installed (???). However, when I go to the switch in Hubitat, I can still turn it on/off (the switch responds accordingly, and the logs show a switch on/off event). Note: I didn't reset the device DB, since I still have basic communication with the devices (but am happy to if that would make a difference here)."

- Could not duplicate testing against the two possible methods that determine install status.
- Note: Just running the app would update the IP addresses.
- Verify:
  - The App version is 6.6.0.  If not, update.
  - The values "LAN Configuration" reflects you lan segment.  Example, if the IP address is 192.168.44.9, the segement is 192.168.44.  also verify that the port is 9999 and the range is 1, 254.

**Comment by snarkywolverine** [comment]
Thanks for your guidance!  The first bullet is solved - I'm not sure why I didn't think of hitting the setPollInterval button after setting a new value.

For (2), I had EM enabled for a lengthy period of time but only saw two jobs - poll, and one that sounded related to energy polling (but it was scheduled for ONCE, not a recurring interval).  I have since disabled EM and will reenable in a little while.

For (3), I'm not so much concerned about that not working as wondering if that was an indication that something isn't right in my environment.

Will update after I reenable energy monitoring on the device.

**Comment by snarkywolverine** [comment]
I had energy monitoring disabled for about an hour yesterday before re-enabling it.  It has now been over 20 hours since re-enabling, and there are no scheduled jobs listed at the bottom of the device page -- how do I get those added/restored?

**Comment by DaveGut** [comment]
- In preferences, select "Enable Energy Monitor"
- Select "Save Preferences"
- Wait 5 minutes then refresh your browser.


The preferences section should look like the below:
![image](https://user-images.githubusercontent.com/25202227/181311646-5d01ae01-a02f-4ff6-b074-af9257ad09af.png)

The ScheduleJobs should look like the below:
![image](https://user-images.githubusercontent.com/25202227/181311842-a3309fcb-036f-4f1f-a9a0-5421c9ce9d8d.png)

**Comment by snarkywolverine** [comment]
Thanks for the screenshot - for some reason "Kasa Cloud Binding" was checked in preferences. After I removed it, I got three of the scheduled jobs, plus a bunch of power events.

I don't see 'getEnergyToday' in my scheduled job list. I'm guessing I shouldn't be concerned?

![image](https://user-images.githubusercontent.com/22400231/181865443-53d2a13d-fb20-49f1-ae62-22a4864dbd5f.png)

Thanks for your help with this!
