### ISSUE TITLE
EP25 Plug Cannot Add

### ISSUE THREAD

**Issue by razor05** [DaveGut/HubitatActive#46]
My Kasa EP25 plugs were not responding anymore, and so I tried to remove and re-add; but when scanning with the deprecated community app for Kasa integration (as that is what I had to do before), they are no longer returned so they can be added.  My older Kasa plugs do.

I tried removing the community app and using the built-in app, but it behaved the same way.

It does appear that Home Assistant was updated to allow the EP25 plugs to be installed - so I was wondering if this is something that can be done in Hubitat as well?

**Comment by DaveGut** [comment]
Try the tapo integration.  You will need to select install kasa hub and .... at top of app.

Dave Gutheinz
________________________________
From: razor05 ***@***.***>
Sent: Sunday, July 21, 2024 9:14:58 PM
To: DaveGut/HubitatActive ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [DaveGut/HubitatActive] EP25 Plug Cannot Add (Issue #46)


My Kasa EP25 plugs were not responding anymore, and so I tried to remove and re-add; but when scanning with the deprecated community app for Kasa integration (as that is what I had to do before), they are no longer returned so they can be added. My older Kasa plugs do.

I tried removing the community app and using the built-in app, but it behaved the same way.

It does appear that Home Assistant was updated to allow the EP25 plugs to be installed - so I was wondering if this is something that can be done in Hubitat as well?

**Comment by razor05** [comment]
> Try the tapo integration.  You will need to select install kasa hub and .... at top of app.
> 
> 
> 
> Dave Gutheinz
> 
> ________________________________
> 
> 

I tried that and it did not work either.

I did note in the debug log that it did fine the plugs, but has an error:

java.lang.IllegalArgumentException: null on line 1059 (method getSmartLanData)

I also saw in the Home Assistant repository that there was an issue last week with authentication, but it was fixed in the latest build of Home Assistant.  Not sure if this is related.

**Comment by razor05** [comment]
________________________________
> > 
> > 
> 
> I tried that and it did not work either.
> 
> I did note in the debug log that it did fine the plugs, but has an error:
> 
> java.lang.IllegalArgumentException: null on line 1059 (method getSmartLanData)
> 
> I also saw in the Home Assistant repository that there was an issue last week with authentication, but it was fixed in the latest build of Home Assistant.  Not sure if this is related.
> 

Figured that the issue above might have been related to the password not being encrypted, so I tried that.  It didn't seem to work (the password was visible in plain text in the debug log)--but the error above didn't occur again, but now it seems like the credentials were not accepted (seems like the same issue that was documented in Home Assistant a few weeks ago):

app:7462024-07-27 03:16:25.447 PMwarntapo_device_install: [method:getAllSmartDeviceData, status:respError, data:[error:credentialError, method:getKlapDeviceData]]
app:7462024-07-27 03:16:25.444 PMwarntapo_device_install: [method:getKlapDeviceData, baseUrl:http://192.168.../app, sessionData:[protocol:KLAP, handshakeValidated:false, status:ERROR], respStatus:FAILED, reason:Login process failure. Check credentials.]
app:7462024-07-27 03:16:25.438 PMinfotapo_device_install: [method:klapLogin, handshake:[method:klapHandshake, localSeed:[33, 104...], uri:http://192.168.../app/handshake1, localHash:[-50, 26,...], errorData:Failed Hash Validation, validated:false]]
app:7462024-07-27 03:16:25.192 PMwarntapo_device_install: [method:getAllSmartDeviceData, status:respError, data:[error:credentialError, method:getKlapDeviceData]]
app:7462024-07-27 03:16:25.188 PMwarntapo_device_install: [method:getKlapDeviceData, baseUrl:http://192.168.../app, sessionData:[protocol:KLAP, handshakeValidated:false, status:ERROR], respStatus:FAILED, reason:Login process failure. Check credentials.]

**Comment by DaveGut** [comment]
Need information:

  1.  GitHub location for the HomeAssisant repository as well as the Problem Report number from same.
  2.  Your EP-25 Hardware Version and Firmware Version.  (Note, the latest version per the TP-Link download center is HW V2.6 and FW V2.6_1.0.2 Build 231108, dated Dec 12, 2023.  I know of successful installations of the EP 25 after that date.
  3.  your next response, first turn-on debug log and provide me with the method: getDiscData entry for your device.  (See Example below).  Note that I need the IP addresses here and in the logs you show below.  That is how I can link the lines to each other.

Observation:  You are not on the current Hubitat integration version (2.3.7b).  Please update.

Known issue:  Tapo Cameras (not support by Integration) can cause an error in the method getDiscData due to recent firmware updates.  If this occurs, unplug your Tapo Cameras and try again. (TAPO is updating the camera security.  It is messed up and part of that update impacts my code.)  Next version will have this error corrected by ignoring all data from cameras.)

Example getDiscData log:  tapo_device_install-2.3.7b: [method:getDiscData, type:SMART.TAPOPLUG, model:P125M(US), baseUrl:http://192.168.50.227:80/app, dni:48225XXXXXA10, devId:630c367e05438181fXXXXXX669aa1c7b, protocol:KLAP, status:OK]


David Gutheinz
214-538-0960

**Comment by razor05** [comment]
Requested information:

1.)
See:  https://github.com/home-assistant/core/issues/121977

And:  https://github.com/home-assistant/core/pull/122089

2.)
HW V2.6 and FW 1.0.3 Build 
145252

3.) debug log:
app:7502024-07-29 12:29:17.714 AMdebugtapo_device_install: [method:getDiscData, type:SMART.KASAPLUG, model:EP25(US), baseUrl:http://192.168.68.160:80/app, dni:50XXXXXXX861, devId:ff32fXXXXXXXXXXXX70a, ip:192.168.68.160, port:80, protocol:KLAP, status:OK]

**Comment by DaveGut** [comment]
1.  Sometime running the discovery again immediately after an error makes the discovery work.  I have never figured out exactly why - but is can solve the problem.  I am looking at this in the next version.
2.  Make sure your credentials are the same as on the TP-Link phone app and that two-factor authentication is turned off.
3.  **After updating integration,**, turn on **debug logging**  in the app and run the install again and send the logs for the EP25 only.  I need both the getDiscData plus any error logs that indicate the issue.

**Comment by DaveGut** [comment]
And: https://github.com/home-assistant/core/pull/122089. : My code already does this.  There is a periodic refresh of each device and part of the error processing works this.  However, this issue DOES NOT impact my app at all.

See: https://github.com/home-assistant/core/issues/121977:  This appears to be something in the specific user's home-assistant configuration.  There have been zero updates to the code and the issue is resolved.

**Comment by razor05** [comment]
I realized that my phone/app auto capitalized the first letter of my username/email; but in the Kasa/TP apps it was all lower case.

When I updated to fully match the case everything worked.

So sorry for not noticing that before.

This issue can be closed - user error.

**Comment by DaveGut** [comment]
It is ok.  I now have another item to mention.

Dave Gutheinz
________________________________
